export const PageUrls = {
	authenticationPage: 'ingresar',
	homePage: '',
	myTickets: 'mis-tickets',
	shoppingCart: 'carro-de-compras',
	buyTickets: 'comprar-tickets',
	enabledMenusList: 'menus-habilitados',
	enableMenu: 'menus/habilitar',
	menusList: 'menus',
	createMenu: 'menus/crear',
	menuDetail: 'menu/:id',
	createDish: 'platos/crear',
	createIngredient: 'ingredientes/crear',
	pageNotFound: 'pagina-no-encontrada',
};